---
title: "rtweet"
author: "Jim Gruman"
date: "2020-12-11"
diagram: true
output: 
 blogdown::html_page:
  toc: false
categories: [R]
description: "Analyze Twitter data" 
image: 
  caption: ''
  focal_point: "Smart"
  preview_only: false
featured: false
draft: false
twitter:
  site: "@jim_gruman"
  creator: "@jim_gruman"
---

<script src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/header-attrs/header-attrs.js"></script>
<script src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/kePrint/kePrint.js"></script>
<link href="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/lightable/lightable.css" rel="stylesheet" />


<p>I was inspired by <a href="https://twitter.com/drob">David Robinson</a>’s Tidy Tuesday screencast to work with <code>rtweet</code> on familiar Twitter handles. Writing on <code>rtweet</code> is an amusing bit of productive procrastination while honing my R skills.</p>
<p>The <code>rtweet</code> package creator and owner, <a href="https://mikewk.com/">Mike Kearney</a>, has hosted data journalism <a href="https://rtweet-workshop.mikewk.com/#1">workshops</a> covering a wide range of uses for this kind of data. They include text sentiment, geospatial networks, time series, and even bot detection. <a href="https://twitter.com/OscarBaruffa">Oscar Baruffa</a> and <a href="https://twitter.com/veerlevanson">Veerle van Son</a> have written a <code>bookdown</code> pamphlet called <a href="https://www.t4rstats.com/">Twitter for R Programmers</a> as a starter guide for people new to the R community on Twitter. Colin Fay has a nice <a href="https://colinfay.me/collect-rtweet/">blog post</a> on his exploration with the {<code>rtweet</code>} package. And on his <code>#30daysmapchallenge</code>, <a href="https://twitter.com/Thoughtfulnz">David Hood</a> put together a super non-geographic map at <a href="https://github.com/thoughtfulbloke/november19_maps/tree/master/nov29">A map of my Twitter readers</a>.</p>
<p>In this post we will look at the accounts that I engage most often, explore the time of day for my Twitter activity, probe for the presence of bots, and close by building an affinity map visualization of my Twitter network following.</p>
<hr />
<p>As with any other project, start with loading the appropriate libraries.</p>
<pre class="r"><code>knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.height = 7.402,
    fig.width = 12,
  fig.align = &quot;center&quot;
)

suppressPackageStartupMessages({

library(tidyverse)   ## tidy data manipulation, including dplyr and ggplot
library(rtweet)     # the R Twitter API 
library(tweetbotornot)  #ML to classify Twitter accounts as bots or not bots. 
library(lubridate)  # date manipulation tools
library(reactable)   # A Formatted Sortable Interactive Table 
library(ggrepel) # adding labels that don&#39;t overlap
library(hexbin) # used for map background
library(umap) # umap dimension reduction
library(here) # helper for directory locations
})
extrafont::loadfonts(quiet = TRUE)

theme_set(hrbrthemes::theme_ft_rc() +
            theme(plot.title.position = &quot;plot&quot;))

pal &lt;- wesanderson::wes_palette(&quot;Zissou1&quot;, 21, type = &quot;continuous&quot;)</code></pre>
<p>The <code>rtweet</code> <a href="http://rtweet.info/articles/auth.html">Obtaining and using access tokens</a> vignette provides instructions for creating API tokens and writing them to a location on <code>.Renviron</code>. This only needs to be done one time.</p>
<hr />
<p>Let’s have a look at the accounts that I favorite (or <strong>like</strong>) the most:</p>
<pre class="r"><code># there is a rate limit at Twitter at approximately 18000 each 15 minutes
df_likes &lt;- rtweet::get_favorites(&quot;jim_gruman&quot;, n = 3000)</code></pre>
<pre class="r"><code>users_favorite &lt;- df_likes %&gt;% 
    group_by(screen_name, user_id) %&gt;%
    summarise(
        quant_fav = n(), .groups = &quot;drop&quot;
    ) %&gt;% 
  arrange(desc(quant_fav))

users_favorite %&gt;%
    slice_max(n = 15, order_by = quant_fav) %&gt;% 
    mutate(screen_name = reorder(screen_name,quant_fav)) %&gt;%
    ggplot(aes(y = screen_name, x = quant_fav, fill = quant_fav)) + 
    geom_col(show.legend = FALSE) +
    theme(text = element_text(hrbrthemes::font_rc, size = 16)) +
    labs(
        title = &quot;The 15 Twitter accounts I &#39;like&#39; the most often&quot;,
        subtitle = paste0(&quot;Within the past 3000 Tweets, since &quot;,min(as_date(df_likes$created_at,  tz = &quot;America/Chicago&quot;))),
        y = &quot;@ user names&quot;,
        x = &quot;# of tweets liked&quot;,
        caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot;|  @jim_gruman&quot;)) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;),
                       limits = c(10,48))</code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-3-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>And let’s break down my activity by week day</p>
<pre class="r"><code>tw_activity &lt;- df_likes %&gt;% 
    transmute(
              tw_hour = hour(as_datetime(created_at, tz = &quot;America/Chicago&quot;)),
              tw_day = as_date(created_at, tz = &quot;America/Chicago&quot;),
              tw_weekday = wday(tw_day,label = T, abbr = T, week_start = 1)
    ) %&gt;%
    group_by(tw_weekday, tw_hour) %&gt;%
    summarise(
        quant_fav = n(), .groups = &quot;drop&quot;,
    ) %&gt;% 
    group_by(tw_weekday) %&gt;% 
    mutate(prop = quant_fav / sum(quant_fav)) %&gt;% 
    ungroup()
  
tw_activity %&gt;%
    ggplot(aes(x = tw_hour, y = prop, fill = prop)) + 
    geom_col(position = position_nudge(x = .5),
             show.legend = FALSE) +
    scale_x_continuous(breaks = c(6, 12, 18)) +
    hrbrthemes::scale_y_percent() +
    facet_wrap(~tw_weekday, ncol = 5) +
    theme(text = element_text(hrbrthemes::font_rc, size = 16),
    panel.grid.minor = element_blank(),
    plot.margin = margin(0.25,0.5,0.25,0.5,&quot;in&quot;)
      ) +
    labs(
        title = &quot;My recent `liking` activity on Twitter&quot;,
        subtitle = paste0(&quot;Within the past 3000 Tweets, since &quot;,min(as.Date(df_likes$created_at, tz = &quot;America/Chicago&quot;))),
        x = &quot;hour of the day&quot;,
        y = &quot;&quot;,
        caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot;|  @jim_gruman&quot;)) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;),
                       limits = c(0.01,0.10))</code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-4-1.png" width="1152" style="display: block; margin: auto;" /></p>
<hr />
<p>To build the map characterizing my social media reach, let’s start by gathering my followers and their details into a dataframe:</p>
<pre class="r"><code>tn &lt;- get_followers(&quot;jim_gruman&quot;) # get my followers
usrs &lt;- lookup_users(tn$user_id) # get my followers full details</code></pre>
<p>Twitter makes a distinction between <strong>followers</strong> and <strong>friends</strong>. My <strong>followers</strong> are accounts that choose to follow my tag, <em><span class="citation">@jim_gruman</span></em>, and see my activity in their news feed (unless muted). At present, it is a list of 2245 user IDs, or “handles.” To capture more information on my followers, my list must be fed into <code>lookup_users()</code>.</p>
<p>We will parse my followers list down somewhat by choosing for accounts in the top 90% of the distribution of counts of both followers and friends. We will also limit the list to those that have posted a tweet, retweet, or favorite at some point in time during the year 2020.</p>
<pre class="r"><code>top_usrs &lt;- usrs %&gt;% 
  filter(followers_count &gt; 
           quantile(usrs$followers_count, 
                    probs = 0.1, na.rm = TRUE),
         friends_count &gt; 
           quantile(usrs$friends_count, 
                    probs = 0.1, na.rm = TRUE),
         as_date(created_at) &gt; dmy(&quot;01-01-2020&quot;))

rm(usrs)</code></pre>
<p>The list drops to 1752 handles to study. My followers in total have 6320554 followers, though the actual number of distinct handles will be less because of overlap. On the surface, this appears to be a reasonably sized challenge.</p>
<hr />
<p>Let’s pause here and take another look at this listing. I am also interested in how many of my followers have chosen bot accounts as friends. Michael Kearney’s <code>tweetbotornot</code> offers a single function for ascertaining probabilities. The default <strong>gradient boosted</strong> model uses both users-level (bio, location, number of followers and friends, etc.) and tweets-level (number of hashtags, mentions, capital letters, etc. in a user’s most recent 100 tweets) data to estimate the probability that users are bots. For larger data sets, the method can be slow. Due to Twitter’s REST API rate limits, users are limited to only 180 estimates per every 15 minutes.</p>
<p>To maximize the number of estimates per 15 minutes (at the cost of being less accurate), we apply the <code>fast = TRUE</code> argument. This method uses only users-level data, which increases the maximum number of estimates per 15 minutes to 90,000, but the accuracy is diminished.</p>
<pre class="r"><code>bots &lt;- tweetbotornot(top_usrs, fast = TRUE) %&gt;% 
  arrange(desc(prob_bot))</code></pre>
<pre class="r"><code>if (file.exists(here(&quot;content/post/rtweet-on-windows/bots.rds&quot;))) {
bots &lt;- read_rds(here(&quot;content/post/rtweet-on-windows/bots.rds&quot;))
} else {
bots &lt;- tweetbotornot(top_usrs, fast = TRUE) %&gt;% 
  arrange(desc(prob_bot))
write_rds(bots, file = here(&quot;content/post/rtweet-on-windows/bots.rds&quot;))
}</code></pre>
<pre class="r"><code>bots %&gt;% 
  filter(prob_bot &gt; 0.9) %&gt;% 
  select(screen_name, prob_bot) %&gt;% 
  knitr::kable(caption = &quot;Likely BOTS that my followers have friended.&quot;) %&gt;% 
  kableExtra::scroll_box(width = &quot;100%&quot;, height = &quot;400px&quot;)</code></pre>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table>
<caption>
<span id="tab:unnamed-chunk-10">Table 1: </span>Likely BOTS that my followers have friended.
</caption>
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
screen_name
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
prob_bot
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
AgLendingGroup
</td>
<td style="text-align:right;">
0.9953
</td>
</tr>
<tr>
<td style="text-align:left;">
DataScienceInR
</td>
<td style="text-align:right;">
0.9917
</td>
</tr>
<tr>
<td style="text-align:left;">
Action6thDistIL
</td>
<td style="text-align:right;">
0.9907
</td>
</tr>
<tr>
<td style="text-align:left;">
JoannaLidback
</td>
<td style="text-align:right;">
0.9901
</td>
</tr>
<tr>
<td style="text-align:left;">
AcrossSpectrum
</td>
<td style="text-align:right;">
0.9885
</td>
</tr>
<tr>
<td style="text-align:left;">
danrejto
</td>
<td style="text-align:right;">
0.9871
</td>
</tr>
<tr>
<td style="text-align:left;">
bikelaneuprise
</td>
<td style="text-align:right;">
0.9867
</td>
</tr>
<tr>
<td style="text-align:left;">
ethancleary
</td>
<td style="text-align:right;">
0.9858
</td>
</tr>
<tr>
<td style="text-align:left;">
blackcow02
</td>
<td style="text-align:right;">
0.9854
</td>
</tr>
<tr>
<td style="text-align:left;">
CherylBozarth
</td>
<td style="text-align:right;">
0.9839
</td>
</tr>
<tr>
<td style="text-align:left;">
Ambient_Intel
</td>
<td style="text-align:right;">
0.9838
</td>
</tr>
<tr>
<td style="text-align:left;">
DataCornering
</td>
<td style="text-align:right;">
0.9836
</td>
</tr>
<tr>
<td style="text-align:left;">
maytownsend
</td>
<td style="text-align:right;">
0.9827
</td>
</tr>
<tr>
<td style="text-align:left;">
fast_crystal
</td>
<td style="text-align:right;">
0.9814
</td>
</tr>
<tr>
<td style="text-align:left;">
dorfman_baruch
</td>
<td style="text-align:right;">
0.9810
</td>
</tr>
<tr>
<td style="text-align:left;">
UnderstandingAg
</td>
<td style="text-align:right;">
0.9809
</td>
</tr>
<tr>
<td style="text-align:left;">
edotosetti
</td>
<td style="text-align:right;">
0.9793
</td>
</tr>
<tr>
<td style="text-align:left;">
SabantoAg
</td>
<td style="text-align:right;">
0.9783
</td>
</tr>
<tr>
<td style="text-align:left;">
CultivationCorr
</td>
<td style="text-align:right;">
0.9769
</td>
</tr>
<tr>
<td style="text-align:left;">
edschober
</td>
<td style="text-align:right;">
0.9763
</td>
</tr>
<tr>
<td style="text-align:left;">
JonEntine
</td>
<td style="text-align:right;">
0.9758
</td>
</tr>
<tr>
<td style="text-align:left;">
Satrdays_DC
</td>
<td style="text-align:right;">
0.9758
</td>
</tr>
<tr>
<td style="text-align:left;">
ComClassic
</td>
<td style="text-align:right;">
0.9740
</td>
</tr>
<tr>
<td style="text-align:left;">
crcgrubbsd
</td>
<td style="text-align:right;">
0.9730
</td>
</tr>
<tr>
<td style="text-align:left;">
StopSterigenics
</td>
<td style="text-align:right;">
0.9723
</td>
</tr>
<tr>
<td style="text-align:left;">
TheRealOG_Dreah
</td>
<td style="text-align:right;">
0.9720
</td>
</tr>
<tr>
<td style="text-align:left;">
VirtualConfere2
</td>
<td style="text-align:right;">
0.9709
</td>
</tr>
<tr>
<td style="text-align:left;">
ChaelMontgomery
</td>
<td style="text-align:right;">
0.9667
</td>
</tr>
<tr>
<td style="text-align:left;">
mikejgraham1
</td>
<td style="text-align:right;">
0.9660
</td>
</tr>
<tr>
<td style="text-align:left;">
brettchase
</td>
<td style="text-align:right;">
0.9660
</td>
</tr>
<tr>
<td style="text-align:left;">
DeconinckKoen
</td>
<td style="text-align:right;">
0.9653
</td>
</tr>
<tr>
<td style="text-align:left;">
HouseAgDems
</td>
<td style="text-align:right;">
0.9642
</td>
</tr>
<tr>
<td style="text-align:left;">
TimeAgro
</td>
<td style="text-align:right;">
0.9628
</td>
</tr>
<tr>
<td style="text-align:left;">
Storm5farms
</td>
<td style="text-align:right;">
0.9626
</td>
</tr>
<tr>
<td style="text-align:left;">
AndyAtLogikk
</td>
<td style="text-align:right;">
0.9608
</td>
</tr>
<tr>
<td style="text-align:left;">
agbiotech
</td>
<td style="text-align:right;">
0.9605
</td>
</tr>
<tr>
<td style="text-align:left;">
TracySchlater
</td>
<td style="text-align:right;">
0.9571
</td>
</tr>
<tr>
<td style="text-align:left;">
soozed
</td>
<td style="text-align:right;">
0.9571
</td>
</tr>
<tr>
<td style="text-align:left;">
sustaincase
</td>
<td style="text-align:right;">
0.9561
</td>
</tr>
<tr>
<td style="text-align:left;">
agrivision_er
</td>
<td style="text-align:right;">
0.9546
</td>
</tr>
<tr>
<td style="text-align:left;">
zerohourclimate
</td>
<td style="text-align:right;">
0.9527
</td>
</tr>
<tr>
<td style="text-align:left;">
CattleTales
</td>
<td style="text-align:right;">
0.9521
</td>
</tr>
<tr>
<td style="text-align:left;">
JoniWallaceML
</td>
<td style="text-align:right;">
0.9514
</td>
</tr>
<tr>
<td style="text-align:left;">
DakotaStandard
</td>
<td style="text-align:right;">
0.9507
</td>
</tr>
<tr>
<td style="text-align:left;">
thalesians
</td>
<td style="text-align:right;">
0.9507
</td>
</tr>
<tr>
<td style="text-align:left;">
wagfarms
</td>
<td style="text-align:right;">
0.9505
</td>
</tr>
<tr>
<td style="text-align:left;">
sermowire
</td>
<td style="text-align:right;">
0.9504
</td>
</tr>
<tr>
<td style="text-align:left;">
iastatejay
</td>
<td style="text-align:right;">
0.9489
</td>
</tr>
<tr>
<td style="text-align:left;">
bwrasa
</td>
<td style="text-align:right;">
0.9489
</td>
</tr>
<tr>
<td style="text-align:left;">
OhioStatePA
</td>
<td style="text-align:right;">
0.9486
</td>
</tr>
<tr>
<td style="text-align:left;">
TiffDowell
</td>
<td style="text-align:right;">
0.9485
</td>
</tr>
<tr>
<td style="text-align:left;">
Superior_Silos
</td>
<td style="text-align:right;">
0.9467
</td>
</tr>
<tr>
<td style="text-align:left;">
FarmGirlJen
</td>
<td style="text-align:right;">
0.9441
</td>
</tr>
<tr>
<td style="text-align:left;">
cncfarms99
</td>
<td style="text-align:right;">
0.9438
</td>
</tr>
<tr>
<td style="text-align:left;">
FarmOpCap
</td>
<td style="text-align:right;">
0.9438
</td>
</tr>
<tr>
<td style="text-align:left;">
paix120
</td>
<td style="text-align:right;">
0.9436
</td>
</tr>
<tr>
<td style="text-align:left;">
hoffsbeefs
</td>
<td style="text-align:right;">
0.9434
</td>
</tr>
<tr>
<td style="text-align:left;">
dmwiebe
</td>
<td style="text-align:right;">
0.9422
</td>
</tr>
<tr>
<td style="text-align:left;">
racheldgantz
</td>
<td style="text-align:right;">
0.9418
</td>
</tr>
<tr>
<td style="text-align:left;">
MarketToMarket
</td>
<td style="text-align:right;">
0.9387
</td>
</tr>
<tr>
<td style="text-align:left;">
AgNews_Otto
</td>
<td style="text-align:right;">
0.9378
</td>
</tr>
<tr>
<td style="text-align:left;">
markbomford
</td>
<td style="text-align:right;">
0.9376
</td>
</tr>
<tr>
<td style="text-align:left;">
twitevit
</td>
<td style="text-align:right;">
0.9367
</td>
</tr>
<tr>
<td style="text-align:left;">
ChannelMktMC
</td>
<td style="text-align:right;">
0.9355
</td>
</tr>
<tr>
<td style="text-align:left;">
kansas_amy
</td>
<td style="text-align:right;">
0.9347
</td>
</tr>
<tr>
<td style="text-align:left;">
Rocks_Gone
</td>
<td style="text-align:right;">
0.9332
</td>
</tr>
<tr>
<td style="text-align:left;">
analytics_post
</td>
<td style="text-align:right;">
0.9329
</td>
</tr>
<tr>
<td style="text-align:left;">
Knuckey_Aus
</td>
<td style="text-align:right;">
0.9327
</td>
</tr>
<tr>
<td style="text-align:left;">
TerryDonahoe2
</td>
<td style="text-align:right;">
0.9321
</td>
</tr>
<tr>
<td style="text-align:left;">
FutureOfAg
</td>
<td style="text-align:right;">
0.9321
</td>
</tr>
<tr>
<td style="text-align:left;">
Mattkohnen1
</td>
<td style="text-align:right;">
0.9320
</td>
</tr>
<tr>
<td style="text-align:left;">
SchrimpfPaul
</td>
<td style="text-align:right;">
0.9314
</td>
</tr>
<tr>
<td style="text-align:left;">
TechHummingbird
</td>
<td style="text-align:right;">
0.9301
</td>
</tr>
<tr>
<td style="text-align:left;">
IHeartAwarenes1
</td>
<td style="text-align:right;">
0.9292
</td>
</tr>
<tr>
<td style="text-align:left;">
WIAgLeader
</td>
<td style="text-align:right;">
0.9288
</td>
</tr>
<tr>
<td style="text-align:left;">
Dougwoolf
</td>
<td style="text-align:right;">
0.9288
</td>
</tr>
<tr>
<td style="text-align:left;">
iWorkMarket
</td>
<td style="text-align:right;">
0.9277
</td>
</tr>
<tr>
<td style="text-align:left;">
TheLANDonline
</td>
<td style="text-align:right;">
0.9264
</td>
</tr>
<tr>
<td style="text-align:left;">
StrathJim
</td>
<td style="text-align:right;">
0.9258
</td>
</tr>
<tr>
<td style="text-align:left;">
sustainablegreg
</td>
<td style="text-align:right;">
0.9241
</td>
</tr>
<tr>
<td style="text-align:left;">
johngaspard
</td>
<td style="text-align:right;">
0.9222
</td>
</tr>
<tr>
<td style="text-align:left;">
riviereagseeds
</td>
<td style="text-align:right;">
0.9217
</td>
</tr>
<tr>
<td style="text-align:left;">
BlakeEarly10
</td>
<td style="text-align:right;">
0.9196
</td>
</tr>
<tr>
<td style="text-align:left;">
GMOInfo_IT
</td>
<td style="text-align:right;">
0.9196
</td>
</tr>
<tr>
<td style="text-align:left;">
shadesnatureinc
</td>
<td style="text-align:right;">
0.9188
</td>
</tr>
<tr>
<td style="text-align:left;">
tylerpaduraru
</td>
<td style="text-align:right;">
0.9187
</td>
</tr>
<tr>
<td style="text-align:left;">
RayLong
</td>
<td style="text-align:right;">
0.9172
</td>
</tr>
<tr>
<td style="text-align:left;">
prometheusgreen
</td>
<td style="text-align:right;">
0.9147
</td>
</tr>
<tr>
<td style="text-align:left;">
MatBonaventure
</td>
<td style="text-align:right;">
0.9146
</td>
</tr>
<tr>
<td style="text-align:left;">
_GypsyCouple
</td>
<td style="text-align:right;">
0.9144
</td>
</tr>
<tr>
<td style="text-align:left;">
mem_somerville
</td>
<td style="text-align:right;">
0.9131
</td>
</tr>
<tr>
<td style="text-align:left;">
IAwateralliance
</td>
<td style="text-align:right;">
0.9131
</td>
</tr>
<tr>
<td style="text-align:left;">
ChiNurse
</td>
<td style="text-align:right;">
0.9126
</td>
</tr>
<tr>
<td style="text-align:left;">
scherms93
</td>
<td style="text-align:right;">
0.9124
</td>
</tr>
<tr>
<td style="text-align:left;">
messykennedy
</td>
<td style="text-align:right;">
0.9120
</td>
</tr>
<tr>
<td style="text-align:left;">
2rkiva
</td>
<td style="text-align:right;">
0.9118
</td>
</tr>
<tr>
<td style="text-align:left;">
MarkLaVenia
</td>
<td style="text-align:right;">
0.9108
</td>
</tr>
<tr>
<td style="text-align:left;">
skyx_agri_swarm
</td>
<td style="text-align:right;">
0.9092
</td>
</tr>
<tr>
<td style="text-align:left;">
HayMapApp
</td>
<td style="text-align:right;">
0.9092
</td>
</tr>
<tr>
<td style="text-align:left;">
RhondaT40
</td>
<td style="text-align:right;">
0.9082
</td>
</tr>
<tr>
<td style="text-align:left;">
HempDirectUSA
</td>
<td style="text-align:right;">
0.9078
</td>
</tr>
<tr>
<td style="text-align:left;">
SteveSprieser
</td>
<td style="text-align:right;">
0.9069
</td>
</tr>
<tr>
<td style="text-align:left;">
HJ_Thompson
</td>
<td style="text-align:right;">
0.9063
</td>
</tr>
<tr>
<td style="text-align:left;">
PerryComGroup
</td>
<td style="text-align:right;">
0.9044
</td>
</tr>
<tr>
<td style="text-align:left;">
IndivisibleNEIA
</td>
<td style="text-align:right;">
0.9041
</td>
</tr>
<tr>
<td style="text-align:left;">
OntFarmerNews
</td>
<td style="text-align:right;">
0.9033
</td>
</tr>
<tr>
<td style="text-align:left;">
fowlerfarms11
</td>
<td style="text-align:right;">
0.9031
</td>
</tr>
<tr>
<td style="text-align:left;">
cmnicholson_
</td>
<td style="text-align:right;">
0.9017
</td>
</tr>
<tr>
<td style="text-align:left;">
Emilycgb
</td>
<td style="text-align:right;">
0.9016
</td>
</tr>
<tr>
<td style="text-align:left;">
CowSpotComm
</td>
<td style="text-align:right;">
0.9004
</td>
</tr>
<tr>
<td style="text-align:left;">
Danialcrig1
</td>
<td style="text-align:right;">
0.9003
</td>
</tr>
</tbody>
</table>
</div>
<p>Let’s also re-create our version of Michael Kearney’s <a href="https://twitter.com/kearneymw/status/1209130912463478788">Polar plot</a> with bots and my favorites accounts from above.</p>
<pre class="r"><code>accounts &lt;- c(pull(users_favorite, screen_name)[1:6],
              pull(bots[1:5,], screen_name),&quot;rstats4ds&quot;)

tmls &lt;- get_timelines(accounts, n = 3000)</code></pre>
<pre class="r"><code>tmls %&gt;% 
  mutate(tw_spot = floor_date(as_datetime(created_at, tz = &quot;America/Chicago&quot;), &quot;10 mins&quot;)) %&gt;% 
  group_by(tw_hour = hour(tw_spot) + minute(tw_spot) / 60,
           bots = if_else(screen_name %in% pull(bots[1:5,], screen_name), TRUE, FALSE),
           screen_name) %&gt;% 
             summarize(activity = log10(n()),
                       .groups = &quot;drop&quot;) %&gt;% 
 ggplot(aes(tw_hour, activity, color = bots)) +
  geom_point(show.legend = FALSE) +
  geom_polygon(show.legend = FALSE) +
  theme(axis.text.y =  element_blank()) +
  coord_polar(theta = &quot;x&quot;) +
  facet_wrap(~ screen_name) +
  labs(title = &quot;Is it a TweetBot or Not?&quot;,
       subtitle = &quot;Tweet frequency by time of day, Chicago time, in 10 minute buckets for last 3000 Tweets&quot;,
       y = &quot;log(TweetCount)&quot;,
       x = &quot;Time of Day&quot;) </code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-12-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>To gather the remaining details of my follower’s connections, we will have to call <code>get_friends()</code> for each of my followers. Twitter has a rate limit. That is, the base API allows 15 requests in a 15 minute period, so the commands are written to pause when it runs out until it can make more requests. With the size of my followers friends lists I expect the process to take around 70 hours, so saving <code>*.csv</code> files is a strategy for restarting if and when problems arise. (Where possible, source this code from a cloud based virtual machine that you can walk away from for a couple of days.)</p>
<pre class="r"><code>allfriends &lt;- function(target_account){
  friendable &lt;- rate_limit(&quot;get_friends&quot;) 
  if (friendable$remaining[1] &lt; 1) {
  Sys.sleep(as.numeric(difftime(friendable$reset_at[1], Sys.time(), units = &quot;secs&quot;)) + 2)
  }
  result &lt;- tryCatch(get_friends(target_account, retryonratelimit = TRUE),
                   error = function(e) NULL, warning = function(w) NULL)
  if (!is.null(result)) {
  write_as_csv(result, file_name = here(&quot;content/post/rtweet-on-windows/fr/&quot;,target_account,&quot;FR.csv&quot;))
  } 
}

still_to_get &lt;- top_usrs$user_id

lapply(still_to_get, allfriends) </code></pre>
<p>To restart the process, ignoring already downloaded follower ID’s, we would execute this code:</p>
<pre class="r"><code>still_to_get &lt;- top_usrs$user_id[!(top_usrs$user_id %in% gsub(&quot;FR.csv&quot;,&quot;&quot;,list.files(path = here(&quot;content/post/rtweet-on-windows/fr/&quot;), pattern=&quot;FR\\.csv&quot;), fixed = TRUE))]

lapply(still_to_get, allfriends) </code></pre>
<p>There may well still be friends lists we can’t get, like private accounts, so we are working only with the publicly available information.</p>
<p>Some while later… 63 hours for me, in fact,
…we read in all the saved csv files and compile them into one list.</p>
<pre class="r"><code>df_relationships &lt;- map_dfr(list.files(path = here(&quot;content/post/rtweet-on-windows/fr/&quot;),
                                       pattern = &quot;FR\\.csv$&quot;, 
                                       full.names = TRUE), read_csv, col_types = &quot;cc&quot;) %&gt;% 
  select(user, user_id) </code></pre>
<pre class="r"><code>df_relationships %&gt;% 
  group_by(user_id) %&gt;%
  mutate(occurances = n()) %&gt;% 
  ungroup() %&gt;% 
  count(user) %&gt;% 
  summarise(entries = sum(n), uniques = n())</code></pre>
<pre><code>## # A tibble: 1 x 2
##   entries uniques
##     &lt;int&gt;   &lt;int&gt;
## 1 3559934    1751</code></pre>
<p>The dataset then represents 3,559,934 relationship pairs for the 1751 (public) top active accounts following <em><span class="citation">@jim_gruman</span></em>.</p>
<p>Because our interest is in finding commonalities in who follows the same accounts, let’s check how large the problem would be if we remove the accounts <strong>only followed by 1 person</strong> in this dataset, as unique accounts, by definition, are not shared with other people.</p>
<pre class="r"><code>df_relationships %&gt;% 
  group_by(user_id) %&gt;%
  mutate(occurances = n()) %&gt;% 
  ungroup() %&gt;% 
  filter(occurances &gt; 1) %&gt;% 
  count(user) %&gt;% 
  summarise(entries = sum(n), uniques = n())</code></pre>
<pre><code>## # A tibble: 1 x 2
##   entries uniques
##     &lt;int&gt;   &lt;int&gt;
## 1 2725818    1751</code></pre>
<p>This simplifies the problem to 2,725,818 relationship pairs, without losing anything that we care about in this analysis. Let’s then turn it from a long list of individual pairs to a wide list of one row for each person that follows me and a column for each account followed by any (2 or more) of my followers.</p>
<p>To apply <code>TSNE</code> or <code>UMAP</code> affinity mapping, the data frame needs to be reshaped into a wide matrix. Given enough time, I would have investigated the <code>sparseMatrix</code> data structure as well.</p>
<pre class="r"><code>wide_relationships &lt;- df_relationships %&gt;% 
  group_by(user_id) %&gt;%
  mutate(occurences = n()) %&gt;% 
  ungroup() %&gt;% 
  filter(occurences &gt; 1) %&gt;% 
  select(-occurences) %&gt;% 
  mutate(weight = 1L) %&gt;%
  pivot_wider(names_from = user_id, 
              values_from = weight, 
              values_fill = 0L)

dim(wide_relationships)</code></pre>
<pre><code>## [1]   1751 318419</code></pre>
<p>With 1751 rows and 318419 columns, where there is a 1 if a person follows the account and a 0 if they do not, we will use dimension reduction techniques to reduce the data frame down to 2 columns for an x and y position to plot. For brevity, will apply the <code>UMAP</code> technique here.</p>
<pre class="r"><code>data_matrix &lt;- as.matrix(wide_relationships[,2:ncol(wide_relationships)])</code></pre>
<p>For building the <code>UMAP</code> reduction, please note that I used an hp Omen Windows laptop with 16 GB of RAM and a 2.2 GHz i7 processor. It took several minutes, towards the end of which the cooling fans were audibly active.</p>
<pre class="r"><code>friends.umap &lt;- umap(data_matrix)
umap &lt;- as.data.frame(friends.umap$layout)

umap$user &lt;- wide_relationships$user</code></pre>
<p>Let’s also explore the amount of cross-following, that is, accounts that follow both me and accounts that follow me, as this has implications in characterizing the spread of information through my social network and the extent of the bubble. If we treat cross-followed accounts as major cites on a map, we need to rank the accounts by how cross-followed they are among those on the list.</p>
<pre class="r"><code>prominence &lt;- df_relationships %&gt;% 
  count(user_id) %&gt;%
  mutate(user_id = str_remove(user_id, &quot;^x&quot;)) 

landmarks &lt;- top_usrs %&gt;% 
  left_join(prominence, by = &quot;user_id&quot;) %&gt;%
  select(user = user_id, screen_name, follows = n) %&gt;% 
  mutate(follows = ifelse(is.na(follows), 0, follows)) 

write_rds(landmarks, file = here(&quot;content/post/rtweet-on-windows/landmarks.rds&quot;))</code></pre>
<p>From here it is a visualization exercise with labels supplied by the landmarks. Let’s see what happens when all of the labels for handles with follows greater than 240 are turned on.</p>
<pre class="r"><code>umap %&gt;% 
  inner_join(landmarks, by = &quot;user&quot;) %&gt;% 
  mutate(screen_name = ifelse(follows &gt; 240, 
                            screen_name, NA)) %&gt;%
  ggplot(aes(V1,V2,size = follows, color = follows)) + 
  geom_point(show.legend = FALSE) +
  labs(title = &quot;Twitter Social Media Following&quot;, subtitle = &quot;UMAP&quot;,
       caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot; @jim_gruman&quot;)) +
  geom_label_repel(aes(label = screen_name), size = 3, color = &quot;black&quot;) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;))</code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-27-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>We can do better.</p>
<p>Let’s take a closer look at the position of a bunch of #AgTwitter and #Rstats accounts, to explore how natural the groups seem to be.</p>
<pre class="r"><code>ag &lt;- c(&quot;MachineryPete&quot;,&quot;lesleyraekelly&quot;,&quot;apasztor82&quot;,
        &quot;PitstickFarms&quot;, &quot;farmermegzz&quot;, &quot;jerodmcdaniel&quot;,
        &quot;jasonmauck1&quot;, &quot;thisfarmwife&quot;, &quot;MGigger&quot;,
        &quot;jwolf7447&quot;,&quot;plowwife&quot;,&quot;ag_guy04&quot;,&quot;sunflowerfarmer&quot;,
        &quot;allison_horst&quot;, &quot;CMastication&quot;)

umap %&gt;% 
  inner_join(landmarks, by = &quot;user&quot;) %&gt;% 
  mutate(screen_name = ifelse(screen_name %in% ag, 
                            screen_name, NA)) %&gt;%
  ggplot(aes(V1,V2,size = follows, color = follows)) + 
  geom_point(show.legend = FALSE) +
  labs(title = &quot;My Twitter Social Media Following&quot;, subtitle = &quot;UMAP&quot;,
       caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot; @jim_gruman&quot;)) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;)) +
  geom_label_repel(aes(label = screen_name), size = 6, color = &quot;black&quot;) </code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-28-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>There may be clustering structure in the cloud, but the image is very busy. How much more effective could a visual using density hexbins be?</p>
<pre class="r"><code>umap %&gt;% 
  inner_join(landmarks, by = &quot;user&quot;) %&gt;% 
  ggplot(aes(V1,V2)) + 
  geom_hex(color = NA) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;))</code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-29-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>The pangea-like quality is visually appealing. Let’s see what can be done with labels or annotations, and a follower count greater than 400.</p>
<pre class="r"><code>umap %&gt;% 
  inner_join(landmarks, by = &quot;user&quot;) %&gt;% 
  mutate(screen_name = ifelse(follows &gt; 400, screen_name, NA_character_),
         xpoint = ifelse(follows &gt; 400, V1, NA),
         ypoint = ifelse(follows &gt; 400, V2, NA),
  ) %&gt;%
  ggplot(aes(x = V1,y = V2)) + 
  geom_hex(color = NA, show.legend = FALSE) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;)) + 
  geom_point(aes(xpoint, ypoint)) +
  geom_label_repel(aes(label = screen_name),
                   size = 3,
                   label.padding = 0.25,
                   box.padding = 2.5) +   
  labs(title = &quot;Where my tweets travel&quot;,
       caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot;|  @jim_gruman&quot;)) </code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-30-1.png" width="1152" style="display: block; margin: auto;" />
Even with the box.padding parameter, it is a challenge to achieve the right balance of labels and visual. Let’s selectively add in accounts that we think are illustrative, as a personal choice.</p>
<pre class="r"><code>cities &lt;- c(&quot;allison_horst&quot;, &quot;CMastication&quot;, &quot;wtfisameme&quot;, &quot;Casein_Micelles&quot;, &quot;AgNews_Otto&quot;,  &quot;SteveSprieser&quot;, &quot;hoffsbeefs&quot;, &quot;eatcookwrite&quot;, &quot;ChrisClaytonDTN&quot;, &quot;jerodmcdaniel&quot;,&quot;agronomistag&quot;, &quot;timhammerich&quot;, &quot;farmermegzz&quot;, &quot;AGofTheWorld&quot;, &quot;RobbFraley&quot;)

umap %&gt;% 
  inner_join(landmarks, by = &quot;user&quot;) %&gt;% 
  mutate(screen_name = if_else(screen_name %in% cities, screen_name, NA_character_),
         cityx = ifelse(screen_name %in% cities, V1, NA)) %&gt;%
  ggplot(aes(V1,V2)) + 
  geom_hex(color = NA, show.legend = FALSE) +
  scale_fill_gradientn(colors = pal,
                       aesthetics = c(&quot;color&quot;,&quot;fill&quot;)) + 
  geom_point(aes(cityx, V2, size = follows), show.legend = FALSE) +
  scale_size_area(max_size = 2) + 
  labs(title = &quot;Where my tweets travel&quot;,
       caption = paste0(format(Sys.Date(), &quot;%b %d, %Y&quot;), &quot; @jim_gruman&quot;)) +
  geom_label_repel(aes(label = screen_name), size = 6) </code></pre>
<p><img src="{{< relref "post/rtweet-on-windows/index.html" >}}index_files/figure-html/unnamed-chunk-31-1.png" width="1152" style="display: block; margin: auto;" /></p>
<hr />
<p>References</p>
<ul>
<li><p>Kearney MW (2019). “rtweet: Collecting and analyzing Twitter data.” Journal of Open Source Software, 4(42), 1829. doi: <a href="https://doi.org/10.21105/joss.01829">10.21105/joss.01829</a>, R package version 0.7.0, <a href="https://joss.theoj.org/papers/10.21105/joss.01829">https://joss.theoj.org/papers/10.21105/joss.01829</a>.</p></li>
<li><p><a href="https://github.com/mkearney/tweetbotornot"><code>tweetbotornot</code></a> package</p></li>
<li><p><a href="https://github.com/thoughtfulbloke/november19_maps/tree/master/nov29">A map of my Twitter readers, by thoughtfulbloke</a></p></li>
</ul>
<hr />
<div id="did-you-find-this-page-helpful-consider-sharing-it" class="section level3">
<h3>Did you find this page helpful? Consider sharing it 🙌</h3>
</div>
